name: 'a action test by wongzz'
on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main


jobs: 
  build: 
    name: build up
    runs-on: ubuntu-latest
    steps:
    - name: check out code 
      uses: actions/checkout@v2
      
    - name: run scripts
      run: sudo bash test.sh
      
